<img src="https://raw.githubusercontent.com/alan-barzilay/NLPortugues/master/imagens/logo_nlportugues.png"   width="150" align="right">


# Introdução ao TensorFlow


_______________

In [1]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.2.0-rc3'

# Tensores

Um [tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor) é um array retangular n-dimensional (uma matriz com _n_ índices) e é o objeto mais basico do TensorFlow. Ele é usado para representar seus dados e faze-los fluir de operação em operação, dai que surgiu o nome TensorFlow.

Nesse notebook você terá uma breve introdução a tensores e como usa-los, para mais detalhes recomendamos olhar o [guia oficial](https://www.tensorflow.org/guide/tensor) da equipe TensorFlow.

-----
Para aqueles que estão familiarizados com numpy, tensores são muito semelhantes a numpy ndarrays, tanto em funcionalidade quanto em utilização.


In [2]:
tf.zeros([2,3,4])  # um vetor com 2 matrizes 3 x 4, zerado

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [3]:
tf.ones([2,3,4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

## Como criar um tensor?

In [4]:
tf.constant([1,2,3])   # esse tensor pode ser visto como um vetor de inteiros de tamanho 3, constante

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
tf.constant(np.array([1,2,3])) # idem, mas o vetor é de long

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [6]:
tf.constant([1,2,3], dtype=np.uint ) #idem, unsigned long

<tf.Tensor: shape=(3,), dtype=uint64, numpy=array([1, 2, 3], dtype=uint64)>

## Constant Vs. Variable
Existem 2 tipos basicos de tensores, [constantes](https://www.tensorflow.org/api_docs/python/tf/constant) e [variaveis](https://www.tensorflow.org/api_docs/python/tf/Variable):
 - Tensores constante estão "escritos em pedra", seus valores não podem ser mais alterados mas podem ser usados como inputs para funções. 
 - Tensores variaveis podem ter seus valores alterados ao realizarmos operações sobre eles, o modulo `tf.keras` os utiliza internamente para representar os pesos de um modelo. Ao inicializarmos um tensor variavel seu `dtype` e `shape` são fixados. Para mais informações, checar este [guia](https://www.tensorflow.org/guide/variable).
 

In [7]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([5,4,3,2,1])

In [8]:
c = a + b

In [9]:
print(c)

tf.Tensor([6 6 6 6 6], shape=(5,), dtype=int32)


In [10]:
print(c.numpy()) # converte o tensor para um array de numpy

[6 6 6 6 6]


In [11]:
a[1:4].numpy()  # slicing em tensores funciona da mesma maneira que em listas

array([2, 3, 4], dtype=int32)

In [12]:
f = tf.Variable([1,2,3,4,5])
f[1].assign(19) # tensores do tipo variaveis podem ter seus conteudos alterados

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 1, 19,  3,  4,  5], dtype=int32)>

In [13]:
a[1].assign(17) # tensores do tipo constante não

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

 Além dessa dicotomia básica também temos 2 outros tipos especiais de tensores:
 - [Ragged Tensors](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor) - São basicamente tensores não retangulares, onde nem todas as dimensoes dos elementos são iguais.
 
 ![alt-text](https://www.tensorflow.org/guide/images/tensor/ragged.png "Ilustração RaggedTensor")
 
 - [Sparce Tensors](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor) - Tensores onde a maioria dos seus elementos são nulos.
 ![alt-text](https://www.tensorflow.org/guide/images/tensor/sparse.png "Ilustração SparceTensor")

# Keras
Como comentado anteriormente, o TensorFlow segue a API do keras. Utilizando as camadas ja existentes no Keras podemos facilmente construir um modelo ao ligarmos elas de maneira sequencial. Uma vez que o modelo esteja definido, basta compila-lo e então treina-lo.
A seguir temos um exemplo minimal de uma rede neural *feedforward*. Para mais informações recomendamos conferir a [documentação oficial](https://keras.io/guides/sequential_model/)


In [14]:
from tensorflow import keras
from tensorflow.keras import layers

In [15]:
model = keras.Sequential(
    [   keras.Input(shape=(4,)),
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4, activation="sigmoid"),
    ]
)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 10        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 9         
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 16        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


Uma maneira alternativa de criarmos um modelo é seguindo a API funcional do Keras, mas como neste momento estamos lidando apenas com modelos simples e sequenciais isso não é necessario. Para mais informações recomendamos conferir a [documentação oficial](https://keras.io/guides/functional_api/)

------------------------------------------------------

__Pergunta:__ Em relação à rede definida, qual é o tamanho da entrada, qual o tamanho da saída, quantas camadas internas e quais são os seus tamanhos? Você seria capaz de desenhá-la?

------------------------------------------------------
Tendo definido nosso modelo, precisamos escolher um *optimizer*, uma função *loss* e compilar ele.
Para mais informações sobre diferentes otimizadores, recomendamos [este post](https://ruder.io/optimizing-gradient-descent/).



```python
model.compile(optimizer= 'rmsprop', loss='binary_crossentropy', metrics = None)
```

Por fim só nos resta treinar nosso modelo

```python

model.fit(x= dados_treino, y= labels_treino, batch_size=32, epochs=300)
```

______________________________

## TF 1.X  Vs TF 2.0

Aqui vamos explorar brevemente alguma das principais diferenças e novidades introduzidas no começo de 2019 com TF 2.0. O contexto aqui apresentado poderá ser util mesmo para alunos que nunca tiveram contato com TF 1.X.

### Eager execution

Em TF 1.X o exemplo que utilizamos acima com `c = a + b` não retornaria o resultado da soma desses 2 tensores, a avaliação das variaveis era adiada até o usuario incializar um objeto session, inicializar as variaveis e em seguida executar cada uma das operações com o método `.run()`.

Isso era feito desta maneira para possibilitar a geração de um grafo onde seus vértices representavam operações e suas arestas tensores fluindo de uma operação a outra. Esse grafo possuia varias utilidades, permitindo uma maior portabilidade dos modelos e maior eficiencia. Porém tornava muito mais dificil de debuggar e encontrar erros no código além de acrescentar *boilerplate code*.

Com a mudança para o TF 2.0 tudo isso mudou visando simplificar a biblioteca, com o objetivo de tornar o codigo mais "pythonico" e semelhante ao resto da linguagem. `Sessions` foram abolidas e eager execution foi ligado por default. Ou seja, ao somarmos 2 tensores essa operação será realizada automaticamente como qualquer operação em python.

Apesar de simplificar sensivelmente a sintaxe, a eficiência do código acabou sendo afetada uma vez que não estamos utilizando os grafos. Para poder disfrutarmos da simplicidade da *eager execution* e da eficiencia do *graphmode*, TF 2.0 introduziu o decorador  `tf.function` e o modo autograph que exploraremos mais a fundo em outro momento. A perda de performance não é grande o suficiente para afetar as analises simples que iremos realizar no começo dessa matéria e, portanto, optamos por deixar os alunos se familiarizarem com o funcionamento do TF 2.0 antes de nos preocuparmos em como otimizar esse código. Além disso, nós só precisamos nos preocupar com  usar `tf.function` em funções que nós mesmos definirmos, de maneira geral todas as funções fornecidas pelo tensorflow já cuidam disso por nós.
Os alunos ansiosos podem conferir o [guia da equipe TensorFlow](https://www.tensorflow.org/guide/function).


### Keras API

A API do Keras `tf.keras` foi instituida como a maneira padrão de se escrever e desenvolver redes neurais em TF2.0. No TensorFlow 1.X isso nem sempre era verdade e podiamos gerar camadas de diversas maneiras distintas. 
Com essa adoção também foi possivel remover diversos métodos duplicados e simplificar consideravelmente a biblioteca.

### `tf.contrib`
Esse modulo foi completamente removido e seus componentes foram redistribuidos e agregados em outros modulos, se você encontrar algum guia ou função que utilize `tf.contrib` saiba que ele se refere ao TF 1.X e pode estar desatualizado.



_______________________________________________________________